
Conversation opened. 1 unread message.

Skip to content
Using IIT Dharwad Mail with screen readers
1 of 10,018
(no subject)
Inbox
Amit Singh
	
5:25 PM (2 minutes ago)
	
to me
build-fifo: fifo.out

fifo.out: fifo.cpp
    g++ -g fifo.cpp -o fifo.out

run-fifo: fifo.out
    ./fifo.out process1.dat

clean-fifo:
    rm fifo.out


build-non_pre_sjf: non_pre_sjf.out

non_pre_sjf.out: non_pre_sjf.cpp
    g++ -g non_pre_sjf.cpp -o non_pre_sjf.out

run-non_pre_sjf: non_pre_sjf.out
    ./non_pre_sjf.out process1.dat

clean-non_pre_sjf:
    rm non_pre_sjf.out


build-pre_sjf: pre_sjf.out

pre_sjf.out: pre_sjf.cpp
    g++ -g pre_sjf.cpp -o pre_sjf.out

run-pre_sjf: pre_sjf.out
    ./pre_sjf.out process1.dat

clean-pre_sjf:
    rm pre_sjf.out

build-round_robin: round_robin.out

round_robin.out: round_robin.cpp
    g++ -g round_robin.cpp -o round_robin.out

run-round_robin: round_robin.out
    ./round_robin.out process1.dat

clean-round_robin:
    rm round_robin.out